# Generated by Django 4.2.13 on 2024-07-06 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("status_code", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("payload", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                ("RepositoryID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255, unique=True)),
                ("Description", models.TextField()),
                ("Link", models.URLField(blank=True)),
                ("CreateTime", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="未评估", max_length=20)),
                (
                    "Owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
