# Generated by Django 5.0.6 on 2024-07-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitRepo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='useraction',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraction',
            name='status_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='useraction',
            table=None,
        ),
    ]
