# Generated by Django 5.0.6 on 2024-07-01 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitRepo', '0002_repository_githublink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='GithubLink',
            new_name='Link',
        ),
    ]
