# Generated by Django 5.0.6 on 2024-07-05 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitRepo', '0002_historicalrepository'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalRepository',
        ),
    ]
