# Generated by Django 5.0.6 on 2024-07-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitRepo', '0003_rename_githublink_repository_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='Name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
