# Generated by Django 5.0.6 on 2024-07-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitRepo', '0004_useraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
