# Generated by Django 5.0.6 on 2024-07-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparkAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repo',
        ),
    ]
