# Generated by Django 4.2.13 on 2024-07-06 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sparkAPI", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodescore",
            name="node",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="score",
                to="sparkAPI.treenode",
            ),
        ),
    ]
