# Generated by Django 4.2.13 on 2024-07-06 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_config", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userconfig",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
