# Generated by Django 4.2.13 on 2024-07-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='api_key',
            field=models.CharField(default='28b98e55ec8e83daddf1e591952e2614', max_length=255),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='api_secret',
            field=models.CharField(default='MGY1MjIzMDk1MTQ4Y2U1YzUxMWI5Yzk1', max_length=255),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='app_id',
            field=models.CharField(default='e8bd2492', max_length=255),
        ),
    ]
